version: '2.1'

services:
  backend_api:
    container_name: backend_api
    build: .
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
    networks:
      - gopamoja

networks:
  gopamoja:
    external: true
