version: '2.1'

services:
  ronaldo:
    container_name: ronaldo
    build: .
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
    networks:
      - gopamoja

networks:
  gopamoja:
    external: true
